image: docker:latest

services:
  - docker:dind

variables:
  API_IMAGE: mechtron/coreys-image-classifier-api
  WEB_IMAGE: mechtron/coreys-image-classifier-web

before_script:
  - apk add --no-cache make
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

stages:
  - build
  # - deploy

build_docker_image_api:
  stage: build
  script:
    - APP_DIR=./api/ IMAGE_NAME=$API_IMAGE COMMIT_TAG=$CI_COMMIT_TAG make docker_image
  only: 
    changes:
      - api/*

# build_docker_image_web:
#   stage: build
#   script:
#     - IMAGE_NAME=$WEB_IMAGE VERSION_TAG=$CI_COMMIT_TAG make docker_image
#   only:
#     changes:
#       - web/*

# deploy_terraform_stage:
#   stage: deploy
#   script:
#     - ENV=dev make run_terragrunt
#   only:
#     - develop

# deploy_terraform_prod:
#   stage: deploy
#   script:
#     - ENV=prod make run_terragrunt
#   only:
#     - master
