version: '3'

services:
  api:
    container_name: classifier_api
    build: ./api
    restart: always
    ports:
     - "8000:8000"
    volumes:
     - ./api:/api
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      REDIS_HOSTNAME: redis
      SECRET_KEY: s3cr3t
    depends_on:
      - mysql
      - redis

  redis:
    container_name: classifier_cache
    image: "redis:alpine"

  mysql:
    container_name: classifier_db
    image: mysql
    ports:
     - "3306:3306"
    volumes:
     - ./db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    container_name: classifier_web
    build:
      context: ./web
      args:
        DEV_ENV: "true"
    restart: always
    ports:
     - "80:80"
    depends_on:
      - api
