apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ml-engineer-project.full_name" . }}
  labels:
    {{- include "ml-engineer-project.release_labels" . | indent 4 }}
data:
  magic-number: '13'
