apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "api_name" . }}
  labels:
    {{- include "release_labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "release_labels" . | indent 8 }}
      annotations:
        checksum/config-map: {{ include (print $.Chart.Name "/templates/config-map.yaml") . | sha256sum }}
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
          - name: MYSQL_HOSTNAME
            value: {{ template "db_name" . }}
          - name: REDIS_HOSTNAME
            value: {{ template "cache_name" . }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "web_name" . }}
  labels:
    {{- include "release_labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "release_labels" . | indent 8 }}
      annotations:
        checksum/config-map: {{ include (print $.Chart.Name "/templates/config-map.yaml") . | sha256sum }}
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
