# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: {{ template "api_name" . }}
# spec:
#   backend:
#     serviceName: {{ template "api_name" . }}
#     servicePort: 8000
#   rules:
#   - http:
#       paths:
#       - path: /api
#         backend:
#           serviceName: {{ template "api_name" . }}
#           servicePort: 8000
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: {{ template "web_name" . }}
# spec:
#   backend:
#     serviceName: {{ template "web_name" . }}
#     servicePort: 80
#   rules:
#   - http:
#       paths:
#       - path: /web
#         backend:
#           serviceName: {{ template "web_name" . }}
#           servicePort: 80
