apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db_name" . }}-password
  labels:
    {{- include "release_labels" . | indent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}