apiVersion: v1
kind: Service
metadata:
  name: {{ template "api_name" . }}
  labels:
    {{- include "release_labels" . | indent 4 }}
spec:
  type: {{ .Values.api.serviceType | default "NodePort" | quote }}
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: {{ template "api_name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "web_name" . }}
  labels:
    {{- include "release_labels" . | indent 4 }}
spec:
  type: {{ .Values.web.serviceType | default "NodePort" | quote }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ template "web_name" . }}