# Generated by Django 2.1.3 on 2018-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.TextField()),
                ('result', models.TextField(max_length=32)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=16)),
                ('processing_type', models.TextField(choices=[('new', 'Image URL being processed for the first time'), ('cached', 'Image URL was previously processed')])),
                ('processing_time', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
    ]
