apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "api_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release_labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "api_name" . }}
        {{- include "release_labels" . | indent 8 }}
      annotations:
        checksum/config-map: {{ include (print $.Chart.Name "/templates/config-map.yaml") . | sha256sum }}
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "api_name" . }}-secret
                key: app-secret
          - name: MYSQL_HOSTNAME
            value: {{ template "db_name" . }}
          - name: MYSQL_USERNAME
            value: {{ .Values.mysql.mysqlUser }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "db_name" . }}-password
                key: mysql-password
          - name: REDIS_HOSTNAME
            value: {{ template "cache_name" . }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "web_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release_labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "web_name" . }}
        {{- include "release_labels" . | indent 8 }}
      annotations:
        checksum/config-map: {{ include (print $.Chart.Name "/templates/config-map.yaml") . | sha256sum }}
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 30
            timeoutSeconds: 5
