apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-db-migrations"
  labels:
    {{- include "releaseLabels" . | indent 8 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ template "name" . }}-db-migrations
    spec:
      restartPolicy: Never
      containers:
      - name: django-migrate
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "apiName" . }}-secret
              key: app-secret
        - name: MYSQL_HOSTNAME
          value: {{ template "dbName" . }}
        - name: MYSQL_USERNAME
          value: {{ .Values.mysql.mysqlUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "dbName" . }}-password
              key: mysql-password
        - name: REDIS_HOSTNAME
          value: {{ template "cacheName" . }}
        command:
         - "python3"
         - "manage.py"
         - "migrate"
