# Waiting for this issue to be fixed before using randAlphaNum N
# to generate secrets: https://github.com/helm/charts/issues/5167

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apiName" . }}-secret
  labels:
    {{- include "releaseLabels" . | indent 4 }}
type: Opaque
data:
  app-secret: {{ .Values.api.apiSecret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dbName" . }}-password
  labels:
    {{- include "releaseLabels" . | indent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
