apiVersion: v1
kind: Secret
metadata:
  name: {{ template "api_name" . }}-secret
  labels:
    {{- include "release_labels" . | indent 4 }}
type: Opaque
data:
  app-secret: {{ .Values.api.apiSecret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db_name" . }}-password
  labels:
    {{- include "release_labels" . | indent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
