apiVersion: v1
kind: Service
metadata:
  name: {{ template "apiName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "releaseLabels" . | indent 4 }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: api_mapping_{{ .Values.name }}
      host: {{ .Values.app_hostname }}
      prefix: /api/
      service: {{ template "apiName" . }}.{{ .Release.Namespace }}:8000
      timeout_ms: 10000
      connect_timeout_ms: 30000
spec:
  type: {{ .Values.api.serviceType | default "NodePort" | quote }}
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    name: {{ template "apiName" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "webName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "releaseLabels" . | indent 4 }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: web_mapping_{{ .Values.name }}
      host: {{ .Values.app_hostname }}
      prefix: /
      service: {{ template "webName" . }}.{{ .Release.Namespace }}:80
      timeout_ms: 10000
      connect_timeout_ms: 30000
spec:
  type: {{ .Values.web.serviceType | default "NodePort" | quote }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: {{ template "webName" . }}
