app_hostname: cic.k8s.sandbox.ggops.com

mysql:
  mysqlDatabase: api
  mysqlUser: classifier
  mysqlPassword: dbpassw0rd # use --set to override this in production

redis:
  cluster:
    enabled: false
  usePassword: false

api:
  image:
    repository: mechtron/coreys-image-classifier-api
    tag: 1.3.1
  serviceType: NodePort
  apiSecret: apis3r3t # use --set to override this in production

web:
  image:
    repository: mechtron/coreys-image-classifier-web
    tag: 1.3.1
  serviceType: NodePort
