app_hostname: classifier.k8s.prod.sandbox.ggops.com

mysql:
  mysqlDatabase: api
  mysqlUser: classifier
  mysqlPassword: dbpassw0rd # use -set to override

redis:
  cluster:
    enabled: false
  usePassword: false

api:
  image:
    repository: mechtron/coreys-image-classifier-api
    tag: v1.0
  serviceType: LoadBalancer
  apiSecret: apis3r3t # use -set to override

web:
  image:
    repository: mechtron/coreys-image-classifier-web
    tag: v1.2
  serviceType: LoadBalancer
