name: CIC workflow
on:
  push:
    branches:
    - master
  create:
    tags:
      - "*"
jobs:
  build_and_deploy_job:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Build API Docker image
      uses: docker/build-push-action@v1
      with:
        path: ./api/
        dockerfile: ./api/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mechtron/coreys-image-classifier-api
        tag_with_ref: true
    - name: Build Web Docker image
      uses: docker/build-push-action@v1
      with:
        path: ./web/
        dockerfile: ./web/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mechtron/coreys-image-classifier-web
        tag_with_ref: true
