name: CIC workflow
on:
  push:
    branches:
    - master
  create:
    tags:
      - "*"
jobs:
  build_and_deploy_job:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Build API Docker image
      uses: docker/build-push-action@v1
      with:
        path: ./api/
        dockerfile: ./api/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mechtron/coreys-image-classifier-api
        tag_with_ref: true
    - name: Build Web Docker image
      uses: docker/build-push-action@v1
      with:
        path: ./web/
        dockerfile: ./web/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mechtron/coreys-image-classifier-web
        tag_with_ref: true
    - name: Deploy Helm chart to EKS
      uses: mechtron/github-actions-ek8s-toolbox@2.0.0
      env:
        API_SECRET: ${{ secrets.API_SECRET }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      with:
        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        awsDefaultRegion: 'us-east-1'
        eksClusterName: ${{ secrets.EKS_CLUSTER_NAME }}
        helmVersion: '3.3.0'
        helmfileVersion: '0.125.7'
        kubectlVersion: '1.18.8'
        istioctlVersion: '1.5.9'
        kubevalVersion: '0.15.0'
        command: |
          helm repo add google https://charts.helm.sh/stable
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency update helm/coreys-image-classifier
          helm upgrade \
            --install classifier \
            --namespace=classifier \
            --create-namespace \
            helm/coreys-image-classifier \
            --set api.apiSecret=$API_SECRET \
            --set mysql.mysqlPassword=$MYSQL_PASSWORD